<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Mdogo' => array($vendorDir . '/gaiagroup/mdogo/src'),
    '' => array($baseDir . '/src', $vendorDir),
);
