<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4b2a715b0c63155cdb9781a11243664a
{
    public static $files = array (
        '0e16ab8105d4f2a89c8aa62e500835e2' => __DIR__ . '/..' . '/gaiagroup/mdogo/mdogo.php',
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'Mdogo' => 
            array (
                0 => __DIR__ . '/..' . '/gaiagroup/mdogo/src',
            ),
        ),
    );

    public static $fallbackDirsPsr0 = array (
        0 => __DIR__ . '/../..' . '/src',
        1 => __DIR__ . '/../..' . '/lib',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit4b2a715b0c63155cdb9781a11243664a::$prefixesPsr0;
            $loader->fallbackDirsPsr0 = ComposerStaticInit4b2a715b0c63155cdb9781a11243664a::$fallbackDirsPsr0;

        }, null, ClassLoader::class);
    }
}
