<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '0e16ab8105d4f2a89c8aa62e500835e2' => $vendorDir . '/gaiagroup/mdogo/mdogo.php',
);
